version: '3.8'

services:
  whisper-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_wisper_v1
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
    env_file:
      - .env
    volumes:
      # Whisperモデルキャッシュを永続化（再ダウンロード防止）
      - whisper_cache:/root/.cache/whisper
      # ログディレクトリ（必要に応じて）
      - ./logs:/app/logs
    restart: unless-stopped
    mem_limit: 8g
    cpus: '2.0'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - whisper_network

volumes:
  whisper_cache:
    driver: local

networks:
  whisper_network:
    driver: bridge 